openapi: 3.0.0

info:
    title: Secure Score Specific Details Plugin
    description: Skills for getting secure score details via Graph API Call
    version: "v1"
servers:
    - url: https://graph.microsoft.com/beta/security
paths:
    /secureScores:
        get:
            operationId: GetSecureScoreDetails
            description: List all secure score details
            responses:
                "200":
                    description: OK
                    content:
                        application/json:
